set(groot, ...
    'DefaultFigureColor', 'w', ...
    'DefaultAxesLineWidth', 2, ...
    'DefaultAxesXColor', 'k', ...
    'DefaultAxesYColor', 'k', ...
    'DefaultAxesFontUnits', 'points', ...
    'DefaultAxesFontSize', 24, ...
    'DefaultAxesFontName', 'Helvetica', ...
    'DefaultLineLineWidth', 2, ...
    'DefaultTextFontUnits', 'Points', ...
    'DefaultTextFontSize', 22, ...
    'DefaultTextFontName', 'Helvetica', ...
    'DefaultAxesBox', 'off', ...
    'DefaultAxesTickLength', [0.02 0.025]);